### PR TITLE
Refactor plumed2 building and testing

### PR DESCRIPTION
**Pull request by raimis**
- [x] Revive Plumed2 tests
  - [x] Clean Conda recipe
- [x] Build Plumed2 with Docker
  - [x] Create a Docker image
  - [x] Integrate with Travis
- [x] Improve uploading to Anaconda
  - [x] Versioning
  - [x] Deployment

### CODE REVIEW

**Comment by tonigi** [comment]
Is the objective still to build a conda package?

**Comment by raimis** [comment]
Yes! Build on Docker and then push to Conda

**Comment by tonigi** [comment]
Ok. By the way we can go to upstream plumed  2.3.3 probably without problems. 
Next release 2.4 will require c++11, not sure if it is supported by  centos:6.9 (g++ 4.4.7)

**Comment by raimis** [comment]
OK! I will update to 2.3.3. For 2.4, we will see later how to overcome!

**Comment by raimis** [comment]
@tonigi, could you check if it makes sense for you, please.

Mac is disabled, as it was not working before and I don't have time now to debug it.

**Comment by tonigi** [comment]
Trying to make a package locally but stops at docker exec build. What is  `${BUILD_VERSION:?}` ?

**Comment by tonigi** [comment]
it was intended. still fixing it.

**Pull request merged**
